config/routes.rb
Rails.application.routes.draw do
  root "assignments#index"
  post "assignments/:id/toggle", to: "assignments#toggle"
  
  resources :assignments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/assignment.rb
class Assignment < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  def index
    @assignments = Assignment.all
    @assignment = Assignment.new
  end

  def create
    @assignment = Assignment.new(assignment_params)

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to assignments_url, notice: "Assignment was successfully created" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def toggle
    @assignment = Assignment.find(params[:id])
    @assignment.update(completed: params[:completed])
  
    render json: { message: "Success" }
  end

  def edit
    @assignment = Assignment.find(params[:id])
  end

  def update
    @assignment = Assignment.find(params[:id])
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to assignments_url, notice: "Task was successfully updated" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @assignment = Assignment.find(params[:id])
    @assignment.destroy
    redirect_to assignments_url, notice: "Post was successfully deleted."
  end

  private

  def assignment_params
    params.require(:assignment).permit(:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_assignment.html.erb
<turbo-frame id="<%= dom_id assignment %>" class="block">
  <%= form_with(model: assignment, class:"text-lg inline-block my-3 w-72") do |form| %>
    <%= form.check_box :completed, data: {
                         id: assignment.id,
                         action: "assignments#toggle"
                       },
                       class: "mr-2 align-middle bg-gray-50 border-gray-300 focus:ring-3 focus:ring-blue-300 h-5 w-5 rounded checked:bg-green-500" %>
    <%= assignment.description %>
  <% end %>

  <%= link_to "Edit", edit_assignment_path(assignment),
              class: "btn bg-gray-100"
  %>
  <div class="inline-block ml-2">
    <%= button_to "Delete", assignment_path(assignment),
                  method: :delete,
                  data: { "turbo-frame": "_top" },
                  class: "btn bg-red-100" %>
  </div>
</turbo-frame>

app/views/assignments/_form.html.erb
<%= form_with(model: assignment, class: "mb-7") do |form| %>
  <div class="mb-5">
    <%= form.text_field :description, placeholder: "Add new task", class: "inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none" %>
    <%= form.submit "Save", class: "btn py-2 ml-2 bg-blue-600 text-white" %>
  </div>
<% end %>

app/views/assignments/edit.html.erb
<div>
  <h1 class="font-bold text-2xl mb-3">Editing Task</h1>

  <turbo-frame id="<%= dom_id @assignment %>">
    <%= render "form", assignment: @assignment %>
    <%= link_to "Never Mind", assignments_path, class: "btn mb-3 bg-gray-100" %>
  </turbo-frame>
</div>

app/views/assignments/index.html.erb
<% if notice.present? %>
  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice">
    <%= notice %>
  </p>
<% end %>

<h1 class="font-bold text-2xl">Task Manager</h1>

<div class="mt-4">
  <%= render "form", assignment: @assignment %>
</div>

<div id="assignments">
  <h1 class="font-bold text-lg mb-7">Tasks</h1>

  <div class="px-5" data-controller="assignments">
    <%= render @assignments %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>